stages:
  - Test

.platform-test:
  stage: Test
  tags:
    - docker
  variables:
    REDIS_URL: 'redis'
    REDIS_PW: 'password'
  services:
  - name: redis:5
    alias: 'redis'
    command: ["redis-server", "--requirepass", "password"]
  script:
    - swift build --build-tests --enable-test-discovery --sanitize=thread -v 
    - swift test --skip-build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $RUN_NIGHTLY'
      allow_failure: true
      when: always
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: always
    